/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.parisnanterre.iqplay;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.junit.jupiter.api.Disabled;
@Disabled
@SpringBootTest
class AppTest {

    @Test
    void isNotEquals() {
        assertNotEquals(2+2, 6);
    }

//    @Test
//    void testMain() {
//        // Checks that the main method doesn't throw an exception
//        assertDoesNotThrow(() -> App.main(new String[] {}));
//    }
}
