services:
  backend:
    build: .
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/game_calcul_mental?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Sami78300!
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - iqplay-network

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Sami78300!
      MYSQL_DATABASE: game_calcul_mental
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql-db"]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - iqplay-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  iqplay-network:

volumes:
  mysql-data: