/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.parisNanterre.FideliTech;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

@SpringBootTest
class AppTest {

    @Test
    void testMain() {
        // Checks that the main method doesn't throw an exception
        assertDoesNotThrow(() -> App.main(new String[] {}));
    }
}
