ifndef::modelsdir[:modeldir: models]

== Team
- Mathieu Baleydier
- Sami Letellier
- Changkai Wang

== Objectif de l'application
L'objectif de cette application est de créer un jeu intelligent dont la difficulté s'ajuste dynamiquement selon les réponses de l'utilisateur. Ce jeu va être utilisé pour concevoir une bibliothèque intelligente facilitant la création de jeux qui se veulent intelligents.

plantuml::src/docs/model/archi.puml[format=svg]

== Routes

=== 1. Démarrer une session de jeu
*URL* : `http://localhost:8080/api/game/start?difficulty=3`

*Méthode* : `GET`

*Paramètres* :
- `difficulty` : Niveau de difficulté (1 à n), type `int`.

*Réponse* :
{ "message": "Session démarrée avec succès.", "sessionId": "6878712f-d9ba-4b92-92a3-b12c7aae0b63" }

*Explication* :
Cette route permet de démarrer une nouvelle session de jeu en fonction du niveau de difficulté choisi. Elle retourne un `sessionId` que vous utiliserez pour toutes les requêtes suivantes liées à cette session.

=== 2. Obtenir une opération à résoudre
*URL* : `http://localhost:8080/api/game/operation/{sessionId}`

*Méthode* : `GET`

*Paramètres* :
- `{sessionId}` : ID de la session obtenue lors du démarrage, type `string`.

*Réponse* :
{ "expression": "20 * 3 - 3 * 7", "result": 39 }

*Explication* :
Cette route renvoie une opération mathématique aléatoire à résoudre ainsi que le résultat de l'expression pour référence interne.

=== 3. Soumettre une réponse à une opération
*URL* : `http://localhost:8080/api/game/answer/{sessionId}?userAnswer={userAnswer}`

*Méthode* : `GET`

*Paramètres* :
- `{sessionId}` : ID de la session de jeu, type `string`.
- `userAnswer` : La réponse donnée par l'utilisateur à l'opération, type `int`.

*Réponse* :
{ "feedback": "Réponse incorrecte ! Le résultat est : 56", "gameStatus": "IN_PROGRESS" }

*Explication* :
Cette route permet à l'utilisateur de soumettre sa réponse. Le serveur vérifie la validité de la réponse et renvoie un retour (correct ou incorrect), ainsi que le statut du jeu.

=== 4. Continuer la partie
*URL* : `http://localhost:8080/api/game/continue/{sessionId}`

*Méthode* : `GET`

*Paramètres* :
- `{sessionId}` : ID de la session de jeu, type `string`.

*Réponse* :
Difficulté mise à jour. Nouvelles opérations générées.

*Explication* :
Cette route permet de continuer le jeu en mettant à jour la difficulté et en générant de nouvelles opérations pour l'utilisateur.

=== 5. Arrêter et terminer une session
*URL* : `http://localhost:8080/api/game/stop/{sessionId}`

*Méthode* : `GET`

*Paramètres* :
- `{sessionId}` : ID de la session de jeu, type `string`.

*Réponse* :
Session terminée et supprimée en mémoire. Le jeu est arrêté.

*Explication* :
Cette route termine la session de jeu et supprime toutes les données associées. Le jeu s'arrête et l'utilisateur ne pourra plus soumettre de réponses ou d'actions jusqu'à ce qu'une nouvelle session soit démarrée.
