name: Build and Upload Documentation

on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: read

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Définir les variables d’environnement
        run: |
          echo "GITHUB_ACTOR=${{ secrets.GH_PACKAGES_USER }}" >> $GITHUB_ENV
          echo "GH_PACKAGES_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }}" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Asciidoctor PDF
        run: ./gradlew build --no-daemon

      - name: Install Doxygen + Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Zip Doxygen documentation
        run: zip -r doxygen-doc.zip docs

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Upload documentation to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" \
            doxygen-doc.zip \
            app/build/docs/asciidoctorPdf/main.pdf#Documentation.pdf \
            --clobber
